apiVersion: securitytower.io/v1alpha1
kind: Application
metadata:
  name: ls-application
spec:
  stages:
    - name: prod
      resources:
        repository: https://github.com/octopus237/Gitops-project-app.git
        revision: main # git branch name
        path: manifests
      targetNamespace: prod
      previousStage: staging
    - name: staging
      resources:
        repository: https://github.com/octopus237/GitOps-project.git
        revision: main
        path: ./
      targetNamespace: prod
